source "https://rubygems.org"

gem "jekyll", ">=3.9.1"
gem "jekyll-watch", ">=2.2.1"
gem 'jekyll-autoprefixer', ">=1.0.0"
gem "jekyll-assets", ">=3.0.0"
gem "execjs", "=2.7.0"
gem "liquid", ">=4.0.3"
gem "pygments.rb", ">=1.2.1"
gem "redcarpet", ">=3.1"
gem "rake", ">=13.0.0"
gem "sass",">=3.7.4"
gem "sass-globbing",">=1.1.0"
gem "uglifier",">=4.1.0"
gem "nokogiri", ">= 1.13.2"
# needed for an incompatibility issue with Jekyll Assets: https://github.com/envygeeks/jekyll-assets/issues/622
gem "sprockets", "~> 3.7"
